### ISSUE TITLE
VoteBot

### ISSUE THREAD

**Issue by Rubiyat82** [DRSchlaubi/mikbot#101]
Hello...  love vote bot.  however, it is not allowing me to vote more than once even though I have said max-votes is 2.

**Comment by DRSchlaubi** [comment]
Did you set the default for max changes or max-changes to >= 1?

**Comment by Rubiyat82** [comment]
I think I did set it for 2.

**Comment by DRSchlaubi** [comment]
max-votes only works when max changes is set to 0
