### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by Harvey-specter1** [DRSchlaubi/mikbot#236]
When i do /create-vote title: but then when i do yes │no it just dosent work, says not enough options

**Comment by Harvey-specter1** [comment]
> When i do /create-vote title: but then when i do yes │no it just dosent work, says not enough options
I just found out is the yes-no function that is for that but still dosent work if i add on with that same line │

**Comment by DRSchlaubi** [comment]
For support please use the votebot support Discord
