### ISSUE TITLE
Votes Stuck at a specific number.

### ISSUE THREAD

**Issue by shahmeer121** [DRSchlaubi/mikbot#275]
Hi there, We at Humanode are utilizing the Votebot for polls in our community. Recently we did a vote for 48 hours and somehow the votes are stuck at 125. New people can't vote even though 5 hours are still left before the voting is closed. The error at my end shows this "The interaction failed." 

How could we resolve this issue?
![Uploading Screenshot 2023-06-23 at 6.35.00 AM.png…]()

**Comment by DRSchlaubi** [comment]
Could you tell me the message link to the poll

**Comment by shahmeer121** [comment]
https://discord.com/channels/819836895739248700/1084857645736939691/1121015832772886608But the poll is in our Sybil-resistant channel so to view it you'll have to get a "Human Verified" role in our server

**Comment by DRSchlaubi** [comment]
The poll seems to be lost from our database, could you check whether the issue happens again if you create a poll with no duration and just close it manually with `/close`

**Comment by shahmeer121** [comment]
What do you mean lost from DB? This is a sensitive poll for contest winners. Gonna cost $2000. Isn't there a way for you to check the issue and resolve this particular poll?

**Comment by DRSchlaubi** [comment]
If a poll ends it gets deleted so all data is gone, it seems like the poll was ended 5 hrs early because of an inaccuracy in system clocks, after that there is nothing I can do

**Comment by shahmeer121** [comment]
Is there a way to check what caused this issue? Coz we are now planning to hold the poll again but want to be 100% sure that it doesn't mess up this time.

**Comment by shahmeer121** [comment]
Want to know if that's an issue with the votebot? Or is it due to any wrong commands?

**Comment by shahmeer121** [comment]
or maybe it has to do something with the vote count?
