### ISSUE TITLE
Multiple Choice possible?

### ISSUE THREAD

**Issue by Tarkinug** [DRSchlaubi/mikbot#79]
Hey I would like to know if we can make multiple choices or if you can add it.

**Comment by DRSchlaubi** [comment]
I think this is more of an issue with Kord-Extensions, which has to support that, since the whole command system is provided by Kordex and not mikbot.

@gdude2002 can we transfer this issue?

**Comment by gdude2002** [comment]
I don't really understand the context of the issue here, can you provide a bit more detail?

**Comment by DRSchlaubi** [comment]
> I don't really understand the context of the issue here, can you provide a bit more detail?

I think he means drop-down menus, but I was about to ask that as well, just couldn't find drop-downs in the documentation.

Are those documented yet?

**Comment by gdude2002** [comment]
Discord calls them select menus, and they are supported in `components { }` builders just like buttons are - `ephemeralSelectMenu` and `publicSelectMenu`, with `unsafeSelectMenu` in the `unsafe` module.
