### ISSUE TITLE
VoteBot: Cannot close a poll after message deletion

### ISSUE THREAD

**Issue by Z8MB1E** [DRSchlaubi/mikbot#86]
It seems that you cannot close a poll in the event that its containing message was deleted. Is there a fix for this? If not, maybe a fix could be implemented wherein attempting to close a poll with a message ID that doesn't exist will simply remove the poll from the list, or something similar?

**Comment by Z8MB1E** [comment]
> The problem is, the retrieval of the message happens before any command logic runs, so the close command has little to change

Is there a way to remove it from the autocompletion list of the slash command `/close` then?

**Comment by DRSchlaubi** [comment]
The auto completion just suggests message links based on what ever is stored in the database, neither does this link need to link to an existing message nor do you need to even select something from autocomplete
